export const SAMPLE_COLLABORATORS = [
  'Giridhar Sundaram',
  'Felix Baughtmer',
  'Sriram Raghu',
  'Vaibhav Wadhwa',
  'Teresa Heikrujam',
];

export const SAMPLE_TASKS = [
  {
    id: 1,
    project: 'BP', // Project identifier or name
    name: 'Design Homepage',
    description: 'Create the initial wireframes and mockups for the homepage.',
    status: 'inprogress',
    priority: 'high',
    assignedTo: 'Alice Johnson',
    dueDate: '2025-10-20',
    createdAt: '2025-10-01T09:00:00Z',
    updatedAt: '2025-10-10T15:30:00Z',
    comments: [
      {
        author: 'Bob',
        text: 'Make sure to use the new branding colors.',
        date: '2025-10-05',
      },
      {
        author: 'Alice Johnson',
        text: 'Wireframes ready for review.',
        date: '2025-10-10',
      },
    ],
    tags: ['design', 'frontend'],
  },
  {
    id: 2,
    project: 'BP',
    name: 'Implement Auth',
    description: 'Build login and registration functionality with JWT tokens.',
    status: 'todo',
    priority: 'medium',
    assignedTo: 'Sriram Raghu',
    dueDate: '2025-10-25',
    createdAt: '2025-10-03T11:00:00Z',
    updatedAt: '2025-10-03T11:00:00Z',
    comments: [],
    tags: ['backend', 'security'],
  },
  {
    id: 3,
    project: 'BP',
    name: 'Write Unit Tests',
    description: 'Cover all user-related features with unit tests.',
    status: 'todo',
    priority: 'low',
    assignedTo: 'Vaibhav Wadhwa',
    dueDate: '2025-11-01',
    createdAt: '2025-10-08T08:00:00Z',
    updatedAt: '2025-10-08T08:00:00Z',
    comments: [],
  },
  {
    id: 4,
    project: 'BP',
    name: 'Set up Database Schema',
    description:
      'Finalize and implement the PostgreSQL database schema for users and tasks.',
    status: 'inprogress',
    priority: 'high',
    assignedTo: 'Giridhar Sundaram',
    dueDate: '2025-10-18',
    createdAt: '2025-10-02T10:00:00Z',
    updatedAt: '2025-10-12T14:00:00Z',
    comments: [
      {
        author: 'Giridhar Sundaram',
        text: 'Initial tables created. Need review on foreign keys.',
        date: '2025-10-12',
      },
    ],
    tags: ['backend', 'database'],
  },
  {
    id: 5,
    project: 'BP',
    name: 'Design Mobile View',
    description:
      'Create responsive designs for all main pages on mobile devices.',
    status: 'todo',
    priority: 'medium',
    assignedTo: 'Felix Baughtmer',
    dueDate: '2025-10-28',
    createdAt: '2025-10-09T14:30:00Z',
    updatedAt: '2025-10-09T14:30:00Z',
    comments: [],
    tags: ['design', 'mobile'],
  },
  {
    id: 6,
    project: 'BP',
    name: 'API Documentation',
    description:
      'Write comprehensive Swagger/OpenAPI documentation for all exposed endpoints.',
    status: 'todo',
    priority: 'low',
    assignedTo: 'Sriram Raghu',
    dueDate: '2025-11-15',
    createdAt: '2025-10-11T09:00:00Z',
    updatedAt: '2025-10-11T09:00:00Z',
    comments: [],
    tags: ['documentation'],
  },
  {
    id: 7,
    project: 'BP',
    name: 'Refactor CSS Module',
    description:
      'Convert legacy CSS files to use CSS Modules for better component isolation.',
    status: 'inprogress',
    priority: 'medium',
    assignedTo: 'Teresa Heikrujam',
    dueDate: '2025-10-22',
    createdAt: '2025-10-04T16:00:00Z',
    updatedAt: '2025-10-10T11:00:00Z',
    comments: [
      {
        author: 'Teresa Heikrujam',
        text: 'About 50% of files migrated. On track.',
        date: '2025-10-10',
      },
    ],
    tags: ['frontend', 'refactor'],
  },
  {
    id: 8,
    project: 'BP',
    name: 'Implement Forgot Password',
    description:
      "Develop the backend endpoint and frontend UI for the 'Forgot Password' flow.",
    status: 'todo',
    priority: 'high',
    assignedTo: 'Vaibhav Wadhwa',
    dueDate: '2025-10-24',
    createdAt: '2025-10-12T10:30:00Z',
    updatedAt: '2025-10-12T10:30:00Z',
    comments: [],
    tags: ['security', 'backend'],
  },
  {
    id: 9,
    project: 'BP',
    name: 'Performance Audit',
    description:
      'Run Lighthouse audit and identify bottlenecks in initial load time.',
    status: 'done',
    priority: 'medium',
    assignedTo: 'Felix Baughtmer',
    dueDate: '2025-10-10',
    createdAt: '2025-10-01T14:00:00Z',
    updatedAt: '2025-10-09T18:00:00Z',
    comments: [
      {
        author: 'Felix Baughtmer',
        text: 'Audit complete. Main issue is unoptimized images.',
        date: '2025-10-09',
      },
    ],
    tags: ['qa', 'performance'],
  },
  {
    id: 10,
    project: 'BP',
    name: 'Optimize Images',
    description: 'Compress and convert all large images to WebP format.',
    status: 'todo',
    priority: 'medium',
    assignedTo: 'Teresa Heikrujam',
    dueDate: '2025-10-27',
    createdAt: '2025-10-10T19:00:00Z',
    updatedAt: '2025-10-10T19:00:00Z',
    comments: [],
    tags: ['frontend', 'performance'],
  },
  {
    id: 11,
    project: 'BP',
    name: 'Integration Tests Setup',
    description: 'Configure Cypress for end-to-end integration testing.',
    status: 'inprogress',
    priority: 'high',
    assignedTo: 'Sriram Raghu',
    dueDate: '2025-10-20',
    createdAt: '2025-10-05T08:30:00Z',
    updatedAt: '2025-10-12T17:00:00Z',
    comments: [
      {
        author: 'Sriram Raghu',
        text: 'Base configuration complete. Writing first test case now.',
        date: '2025-10-12',
      },
    ],
    tags: ['testing', 'devops'],
  },
  {
    id: 12,
    project: 'BP',
    name: 'Implement Task Filtering',
    description:
      'Add filtering functionality to the task list (by status, priority, and assignee).',
    status: 'todo',
    priority: 'high',
    assignedTo: 'Alice Johnson',
    dueDate: '2025-10-26',
    createdAt: '2025-10-13T10:00:00Z',
    updatedAt: '2025-10-13T10:00:00Z',
    comments: [],
    tags: ['frontend', 'data'],
  },
  {
    id: 13,
    project: 'BP',
    name: "Create 'New Task' Form",
    description:
      'Develop the form component for creating new tasks with validation.',
    status: 'done',
    priority: 'medium',
    assignedTo: 'Vaibhav Wadhwa',
    dueDate: '2025-10-12',
    createdAt: '2025-10-06T12:00:00Z',
    updatedAt: '2025-10-11T16:00:00Z',
    comments: [
      {
        author: 'Vaibhav Wadhwa',
        text: 'Form component finished and merged.',
        date: '2025-10-11',
      },
    ],
    tags: ['frontend', 'component'],
  },
  {
    id: 14,
    project: 'BP',
    name: 'Setup CI/CD Pipeline',
    description:
      'Configure GitHub Actions/GitLab CI for automated build and deployment to staging.',
    status: 'todo',
    priority: 'medium',
    assignedTo: 'Giridhar Sundaram',
    dueDate: '2025-11-05',
    createdAt: '2025-10-13T12:00:00Z',
    updatedAt: '2025-10-13T12:00:00Z',
    comments: [],
    tags: ['devops', 'automation'],
  },
  {
    id: 15,
    project: 'BP',
    name: 'Review Wireframes',
    description: 'Team review of the initial homepage wireframes (Task 1).',
    status: 'done',
    priority: 'low',
    assignedTo: 'Felix Baughtmer',
    dueDate: '2025-10-06',
    createdAt: '2025-10-04T10:00:00Z',
    updatedAt: '2025-10-06T15:00:00Z',
    comments: [],
    tags: ['design', 'review'],
  },
  {
    id: 16,
    project: 'BP',
    name: 'Add Error Logging',
    description: 'Integrate Sentry or another error tracking service.',
    status: 'todo',
    priority: 'medium',
    assignedTo: 'Giridhar Sundaram',
    dueDate: '2025-10-30',
    createdAt: '2025-10-14T09:00:00Z',
    updatedAt: '2025-10-14T09:00:00Z',
    comments: [],
    tags: ['backend', 'tooling'],
  },
  {
    id: 17,
    project: 'BP',
    name: 'Implement Notifications',
    description: 'Develop system for user notifications on task changes.',
    status: 'inprogress',
    priority: 'high',
    assignedTo: 'Sriram Raghu',
    dueDate: '2025-11-03',
    createdAt: '2025-10-10T13:00:00Z',
    updatedAt: '2025-10-13T16:00:00Z',
    comments: [],
    tags: ['backend', 'feature'],
  },
  {
    id: 18,
    project: 'BP',
    name: 'Design Empty States',
    description: 'Create designs for empty task lists, search results, etc.',
    status: 'todo',
    priority: 'low',
    assignedTo: 'Felix Baughtmer',
    dueDate: '2025-11-10',
    createdAt: '2025-10-15T09:00:00Z',
    updatedAt: '2025-10-15T09:00:00Z',
    comments: [],
    tags: ['design', 'ux'],
  },
  {
    id: 19,
    project: 'BP',
    name: 'Accessibility (A11y) Check',
    description: 'Audit main pages for WCAG compliance and fix any issues.',
    status: 'todo',
    priority: 'medium',
    assignedTo: 'Teresa Heikrujam',
    dueDate: '2025-11-08',
    createdAt: '2025-10-16T11:00:00Z',
    updatedAt: '2025-10-16T11:00:00Z',
    comments: [],
    tags: ['a11y', 'frontend'],
  },
  {
    id: 20,
    project: 'BP',
    name: 'Develop User Profile Page',
    description:
      'Implement the frontend and API integration for the user profile view.',
    status: 'inprogress',
    priority: 'high',
    assignedTo: 'Vaibhav Wadhwa',
    dueDate: '2025-10-23',
    createdAt: '2025-10-07T14:00:00Z',
    updatedAt: '2025-10-14T10:00:00Z',
    comments: [],
    tags: ['frontend', 'feature'],
  },
  {
    id: 21,
    project: 'BP',
    name: 'Final Project Review',
    description:
      'Executive review of project goals and scope for final delivery.',
    status: 'done',
    priority: 'low',
    assignedTo: 'Giridhar Sundaram',
    dueDate: '2025-10-01',
    createdAt: '2025-09-25T09:00:00Z',
    updatedAt: '2025-10-01T14:00:00Z',
    comments: [
      {
        author: 'Giridhar Sundaram',
        text: 'Review passed. Remaining tasks are ready for development.',
        date: '2025-10-01',
      },
    ],
    tags: ['management'],
  },
  {
    id: 22,
    project: 'BP',
    name: 'Setup Production Environment',
    description:
      'Provision and configure AWS/Azure environment for production deployment.',
    status: 'todo',
    priority: 'high',
    assignedTo: 'Sriram Raghu',
    dueDate: '2025-11-10',
    createdAt: '2025-10-17T12:00:00Z',
    updatedAt: '2025-10-17T12:00:00Z',
    comments: [],
    tags: ['devops', 'cloud'],
  },
  {
    id: 23,
    project: 'BP',
    name: 'Update README/Installation Guide',
    description:
      "Ensure the project's documentation is up-to-date with installation instructions.",
    status: 'todo',
    priority: 'low',
    assignedTo: 'Teresa Heikrujam',
    dueDate: '2025-11-20',
    createdAt: '2025-10-18T10:00:00Z',
    updatedAt: '2025-10-18T10:00:00Z',
    comments: [],
    tags: ['documentation'],
  },
];

export const SAMPLE_ATTACHMENTS = [
  {
    document:
      'https://images.unsplash.com/photo-1503023345310-bd7c1de61c7d?auto=format&fit=crop&w=800&q=80',
    type: 'img',
    name: 'Sunset over the mountains',
    taskId: '1',
    taskName: 'Design Homepage',
    project: 'LP',
  },
  {
    document:
      'https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=800&q=80',
    type: 'img',
    name: 'Forest Path',
    taskId: '2',
    name: 'Implement Auth',
    project: 'LP',
  },
  {
    document:
      'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80',
    type: 'img',
    name: 'Mountain Lake',
    taskId: '3',
    taskName: 'Write Unit Tests',
    project: 'LP',
  },
  {
    document:
      'https://images.unsplash.com/photo-1468071174046-657d9d351a40?auto=format&fit=crop&w=800&q=80',
    type: 'img',
    name: 'Beach View',
    taskId: '4',
    taskName: 'Set up Database Schema',
    project: 'LP',
  },
  {
    document:
      'https://images.unsplash.com/photo-1499951360447-b19be8fe80f5?auto=format&fit=crop&w=800&q=80',
    type: 'img',
    name: 'Cityscape',
    taskId: '5',
    taskName: 'Design Mobile View',
    project: 'LP',
  },
  //   {
  //     document:
  //       'https://file-examples-com.github.io/uploads/2017/10/file-example_PDF_1MB.pdf',
  //     type: 'pdf',
  //     name: 'Sample PDF 1MB',
  //     taskId: '6',
  //     project: 'LP',
  //   },
  //   {
  //     document:
  //       'https://file-examples-com.github.io/uploads/2017/10/file-example_PDF_500_kB.pdf',
  //     type: 'pdf',
  //     name: 'Sample PDF 500KB',
  //     taskId: '7',
  //     project: 'LP',
  //   },
  {
    document:
      'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=800&q=80',
    type: 'img',
    name: 'Desert Dunes',
    taskId: '8',
    taskName: 'Implement Forgot Password',
    project: 'LP',
  },
  //   {
  //     document:
  //       'https://file-examples-com.github.io/uploads/2017/10/file-sample_150kB.pdf',
  //     type: 'pdf',
  //     name: 'Sample PDF 150KB',
  //     taskId: '9',
  //     project: 'LP',
  //   },
  {
    document:
      'https://images.unsplash.com/photo-1462331940025-496dfbfc7564?auto=format&fit=crop&w=800&q=80',
    type: 'img',
    name: 'City Skyline',
    taskId: '10',
    taskName: 'Optimize Images',
    project: 'LP',
  },
];

export const SAMPLE_PROJECT_DATA = {
  projectId: 1,
  collaborators: [...SAMPLE_COLLABORATORS],
  tasks: [...SAMPLE_TASKS],
};
